site_name: FaBo JetFormer Docs
copyright: "© FaBo"
theme:
    name: material
    custom_dir: 'theme'
    language: 'ja'
    palette:
      primary: 'green'
      accent: 'black'
    logo: 'logo.png'
    favicon: 'favicon.png'
extra:
    search:
        language: 'jp'
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      noclasses: false
      pygments_style: monokai
      linenums: true
  - pymdownx.superfences
  - admonition
  - pymdownx.keys
  - attr_list
nav:
  - Home: "index.md"
  - 1.はじめに: "jetformer/基礎編/start.md"
  - JetRacer:
    - 基本編:
      - 1.GettingStarted: "jetformer/基礎編/01.intro.md"
    - 項目別:
      - 1.使用するNotebook: "jetformer/各項目/01.notebooks.md"
      - 2.PWMの設定: "jetformer/各項目/02.pwm.md"
      - 3.走行録画: "jetformer/各項目/09.recordCamera.md"
      - 4.画像カット: "jetformer/各項目/03.filecut.md"
      - 5.アノテーションと学習: "jetformer/各項目/03.interactive_regression.md"
      - 6.TensorRTへの変換: "jetformer/各項目/04.optimize_model.md"
      - 7.自動走行: "jetformer/各項目/05.run.md"
      - 8.クラウドによる学習: "jetformer/各項目/08.googleColab.md"
      - 9.受信機信号計測: "jetformer/各項目/10.transmitterSignal.md"
      - 10.検証動画作成: "jetformer/各項目/11.makeMovie.md"
      - 11.アノテーション: "jetformer/各項目/07.remark.md"
      - 12.環境情報判断: "jetformer/各項目/12.EnvironmentalJudgment.md"
    - 設定:
      - 1.Wi-Fiの設定: "jetformer/設定/01.wifi.md"
      - 2.Windowsの設定: "jetformer/設定/02.win.md"
    - 各種Tips:
      - 1.Tips: "jetformer/各種Tips/01.tips.md"


extra_css:
#  - "https://fonts.googleapis.com/earlyaccess/notosansjp.css"
#  - "https://fonts.googleapis.com/css?family=Open+Sans:600,800"
  - "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
#  - "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css"
  - "css/version-select.css"
  - "css/custom.css"
extra_javascript:
  - javascripts/version-select.js
  - javascripts/extra.js
plugins:
  - macros
  - with-pdf:
      author: FaBo
      cover_title: FaBo JetFormer Docs
      cover_subtitle: JetFormer ドキュメント
      toc_title: 目次
      output_path: pdf/jetformer-docs.pdf
      enabled_if_env: ENABLE_PDF_EXPORT